const $=id=>document.getElementById(id),data=window.CATALOG,key='data-atlas-notes-v1',states=['未标记','待核对','待合并','暂保留','已整理'];
let notes={},page=0,active=null,project=null,category='';const pageSize=30;
try{const v=JSON.parse(localStorage.getItem(key)||'{}');if(v&&typeof v==='object'&&!Array.isArray(v))notes=v}catch(e){$('message').textContent='存储不可用，请导出备注备份。'}
function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}
function noteKey(a){return 'asset:'+a.id}
function saved(a){return notes[noteKey(a)]||a.locations.map(l=>notes[l.path]).find(Boolean)||{}}
function state(a){return saved(a).status||'未标记'}
function home(){const q=$('project-search').value.toLowerCase();$('projects').replaceChildren();for(const type of ['项目','共享数据','辅助工具']){const found=data.projects.filter(p=>p.type===type&&[p.name,...p.assets.map(a=>a.relative_path)].join(' ').toLowerCase().includes(q));if(!found.length)continue;$('projects').append(node('h2',`${type} · ${found.length}`,'group-heading'));for(const p of found){const c=node('button','','project-card');c.append(node('strong',p.name),node('span',`${p.assets.filter(a=>a.category!=='项目入口').length} 个逻辑目录`),node('small',Object.entries(p.counts).filter(([k])=>k!=='项目入口').map(([k,v])=>`${k} ${v}`).join(' · ')||'仅登记项目入口，尚无独立数据目录'));c.onclick=()=>openProject(p);$('projects').append(c)}}}
function openProject(p){project=p;category='';page=0;$('projects').hidden=true;$('project-search').parentElement.hidden=true;$('workspace').hidden=false;$('project-title').textContent=p.name;$('project-summary').textContent='同一相对目录的本机与 NAS 位置集中登记，并未认定内容重复。父子目录可能重叠，目录数量不代表独立数据集数量。';$('origin').replaceChildren(node('option','全部来源'));$('origin').firstChild.value='';for(const origin of [...new Set(p.assets.flatMap(a=>a.locations.map(l=>l.origin)))].sort()){const o=node('option',origin);o.value=origin;$('origin').append(o)}$('search').value='';$('status').value='';render();$('workspace').scrollIntoView({behavior:'smooth'})}
function filtered(){const q=$('search').value.toLowerCase();return project.assets.filter(a=>(!category||a.category===category)&&(!$('origin').value||a.locations.some(l=>l.origin===$('origin').value))&&(!$('status').value||state(a)===$('status').value)&&[a.relative_path,a.category,...a.locations.map(l=>l.path),saved(a).note||''].join(' ').toLowerCase().includes(q))}
function render(){const all=data.projects.flatMap(p=>p.assets);$('stats').replaceChildren();for(const [label,value] of [['项目入口',data.projects.filter(p=>p.type==='项目').length],['共享数据入口',data.projects.filter(p=>p.type==='共享数据').length],['已分类数据目录',all.filter(a=>!['项目入口','混合目录／待确认'].includes(a.category)).length],['混合 / 待确认目录',all.filter(a=>a.category==='混合目录／待确认').length]]){const c=node('div','','stat');c.append(node('span',label),node('strong',value));$('stats').append(c)}if(!project)return;
 $('categories').replaceChildren();for(const cat of ['',...data.categories]){const n=cat?project.counts[cat]||0:project.assets.length;if(!n&&cat)continue;const b=node('button',`${cat||'全部'} ${n}`,cat===category?'active':'');b.onclick=()=>{category=cat;page=0;render()};$('categories').append(b)}
 const found=filtered(),pages=Math.max(1,Math.ceil(found.length/pageSize));page=Math.min(page,pages-1);$('rows').replaceChildren();for(const a of found.slice(page*pageSize,(page+1)*pageSize)){const tr=node('tr',''),first=node('td',a.relative_path);first.append(node('small',a.reason));tr.append(first,node('td',a.category));const pos=node('td','');for(const l of a.locations)pos.append(node('small',l.origin),node('div',l.path,'path'));tr.append(pos);const s=node('td','');s.append(node('span',state(a),'badge'));tr.append(s);const c=node('td',''),b=node('button','详情 / 备注');b.onclick=()=>detail(a);c.append(b);tr.append(c);$('rows').append(tr)}$('count').textContent=`${found.length} 个逻辑目录（含父子层级）`;$('page').textContent=`${page+1} / ${pages}`;$('prev').disabled=page===0;$('next').disabled=page===pages-1}
function detail(a){active=a;$('title').textContent=project.name+' / '+a.relative_path;$('fields').replaceChildren();for(const [label,value] of [['分类',a.category],['分类依据',a.reason],['完整性','目录级登记；没有逐文件核验，不代表传输已完成'],['索引时间',data.indexed_at],...a.locations.map(l=>[l.origin+(l.sampled?'（来自子目录抽样）':''),l.path])])$('fields').append(node('dt',label),node('dd',value));for(const l of a.locations.filter(l=>notes[l.path]))$('fields').append(node('dt','旧版位置备注：'+l.path),node('dd',(notes[l.path].status||'')+' '+(notes[l.path].note||'')));$('edit-status').value=state(a);$('note').value=saved(a).note||'';$('detail').showModal()}
function persist(){try{localStorage.setItem(key,JSON.stringify(notes));$('message').textContent='备注已保存于当前浏览器。'}catch(e){$('message').textContent='保存失败，请导出备注备份。'}render()}
$('save').onclick=()=>{notes[noteKey(active)]={status:$('edit-status').value,note:$('note').value,updated:new Date().toISOString()};persist();$('detail').close()};
for(const id of ['search','origin','status'])$(id).addEventListener('input',()=>{page=0;render()});
$('project-search').oninput=home;$('close-project').onclick=()=>{project=null;$('workspace').hidden=true;$('projects').hidden=false;$('project-search').parentElement.hidden=false;home()};
$('reset').onclick=()=>{for(const id of ['search','origin','status'])$(id).value='';category='';page=0;render()};$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};
$('export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({version:1,notes},null,2)],{type:'application/json'})),a=node('a','');a.href=u;a.download='data-atlas-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('import').onclick=()=>$('import-file').click();$('import-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const n=JSON.parse(await f.text());if(n.version!==1||!n.notes||typeof n.notes!=='object')throw Error();const valid=new Set([...data.entries.map(r=>r.path),...data.projects.flatMap(p=>p.assets.flatMap(a=>[noteKey(a),...a.locations.map(l=>l.path)]))]);let count=0;for(const [path,v] of Object.entries(n.notes)){if(valid.has(path)&&v&&states.includes(v.status)&&typeof v.note==='string'){notes[path]={status:v.status,note:v.note.slice(0,20000),updated:v.updated};count++}}persist();$('message').textContent=`已导入 ${count} 条备注。`}catch(e){$('message').textContent='导入失败：请选择本站导出的备注 JSON。'}e.target.value=''};
$('updated').textContent=new Date(data.indexed_at).toLocaleString('zh-CN');$('mode').textContent=data.public_mode?'精简索引（隐藏绝对路径）':'本地完整索引';home();render();
