const $=id=>document.getElementById(id), data=window.CATALOG, key='data-atlas-notes-v1';
const states=['未标记','待核对','待合并','暂保留','已整理'];
let notes={},page=0,active=null;const pageSize=40;
try{notes=JSON.parse(localStorage.getItem(key)||'{}')}catch(e){$('message').textContent='浏览器存储不可用；请及时导出备注。'}
function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}
function state(r){return notes[r.path]?.status||'未标记'}
function filtered(){const q=$('search').value.toLowerCase();return data.entries.filter(r=>(!$('origin').value||r.origin===$('origin').value)&&(!$('status').value||state(r)===$('status').value)&&[r.project,r.path,r.kind,r.origin,(notes[r.path]?.note||'')].join(' ').toLowerCase().includes(q))}
function render(){const found=filtered(),pages=Math.max(1,Math.ceil(found.length/pageSize));page=Math.min(page,pages-1);$('rows').replaceChildren();for(const r of found.slice(page*pageSize,(page+1)*pageSize)){const tr=node('tr',''),a=node('td',r.project);a.append(node('small',r.kind));tr.append(a,node('td',r.origin),node('td',r.path,'path'));const b=node('td','');b.append(node('span',state(r),'badge'));tr.append(b);const c=node('td',''),button=node('button','详情');button.onclick=()=>detail(r);c.append(button);tr.append(c);$('rows').append(tr)}$('count').textContent=`${found.length} 条目录记录`;$('page').textContent=`${page+1} / ${pages}`;$('prev').disabled=page===0;$('next').disabled=page===pages-1;$('stats').replaceChildren();for(const [label,value] of [['目录记录',data.entries.length],['项目 / 城市分组',new Set(data.entries.map(r=>r.project)).size],['来源类别',new Set(data.entries.map(r=>r.origin)).size],['待核对 / 待合并',data.entries.filter(r=>['待核对','待合并'].includes(state(r))).length]]){const c=node('div','','stat');c.append(node('span',label),node('strong',value));$('stats').append(c)}}
function detail(r){active=r;$('title').textContent=r.project;$('fields').replaceChildren();for(const [label,value] of [['位置',r.path],['对应目录',r.counterpart||'未登记'],['目录链接目标',r.directory_link||'无 / 未公开'],['子目录（抽样）',(r.children||[]).join('、')||'未登记'],['完整性',r.completeness],['目录抽样截断',r.listing_truncated?'是；此处不是完整清单':'否'],['索引时间',r.indexed_at]]){$('fields').append(node('dt',label),node('dd',value))}$('edit-status').value=state(r);$('note').value=notes[r.path]?.note||'';$('detail').showModal()}
function persist(){try{localStorage.setItem(key,JSON.stringify(notes));$('message').textContent='备注已保存在当前浏览器，不会修改 NAS 文件。'}catch(e){$('message').textContent='保存失败，请立即导出备注备份。'}render()}
$('save').onclick=()=>{notes[active.path]={status:$('edit-status').value,note:$('note').value,updated:new Date().toISOString()};persist();$('detail').close()};
for(const id of ['search','origin','status'])$(id).addEventListener('input',()=>{page=0;render()});
$('reset').onclick=()=>{for(const id of ['search','origin','status'])$(id).value='';page=0;render()};$('prev').onclick=()=>{page--;render()};$('next').onclick=()=>{page++;render()};
$('export').onclick=()=>{const u=URL.createObjectURL(new Blob([JSON.stringify({version:1,notes},null,2)],{type:'application/json'})),a=node('a','');a.href=u;a.download='data-atlas-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
$('import').onclick=()=>$('import-file').click();$('import-file').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const n=JSON.parse(await f.text());if(n.version!==1||!n.notes||typeof n.notes!=='object')throw Error();const valid=new Set(data.entries.map(r=>r.path));let count=0;for(const [path,v] of Object.entries(n.notes)){if(valid.has(path)&&v&&states.includes(v.status)&&typeof v.note==='string'){notes[path]={status:v.status,note:v.note.slice(0,20000),updated:v.updated};count++}}persist();$('message').textContent=`已导入 ${count} 条备注。`}catch(e){$('message').textContent='导入失败：请选择本站导出的备注 JSON。'}e.target.value=''};
for(const origin of [...new Set(data.entries.map(r=>r.origin))].sort()){const o=node('option',origin);o.value=origin;$('origin').append(o)}
$('updated').textContent=new Date(data.indexed_at).toLocaleString('zh-CN');$('mode').textContent=data.public_mode?'精简索引（隐藏绝对路径）':'本地完整索引';render();
